# random 기능들

> numpy 모듈
- np.random.choice(list) : list에서 1개 난수 꺼내기-> int
- np.random.normal(): 가우시안 분포내에서 난수 꺼내기 -> float
- np.random.rand(shape) : 0~1의 범위에서 uniform한 분포에서 shape만큼 array 생성 -> float
- np.random.randint(low, high) : low ~ high내의 정수 1개 생성 -> int
- np.random.randint(shape) : 표준 정규 분포에서 shape만큼 난수 생성 -> float
- np.random.random(size) : [ 0.0, 1.0 )의 범위에서 size만큼 난수 생성 -> flo


> random 모듈
- random.shuffle(list) : list 내 원소 섞기 -> none 반환
- random.choice(list) : list내 원소 1개 꺼내기
- random.randint(low, high): low~high 내에서 정수 1개 반환 -> int
- random.random() : 0~1내 실수 랜덤 생성: float
- random.randrange(srart,end, step): start에서 end까지 step 만큼 떨어진 수 중 랜덤으로 선택
- random.sample(list, size): list 내에서 size만큼 생성

## 1. numpy 

In [2]:
import numpy as np

In [8]:
np.random.choice(a)

5

In [11]:
np.random.normal()

-0.06318002573253169

In [16]:
np.random.rand(1,2,3)

array([[[0.47756351, 0.12063058, 0.0722429 ],
        [0.55176048, 0.24808377, 0.80295513]]])

In [17]:
np.random.randint(0, 10)

6

In [21]:
np.random.randn(1,2)

array([[-1.32131238, -0.78830792]])

In [22]:
np.random.random(8)

array([0.01472994, 0.26301342, 0.41940707, 0.37666501, 0.61065401,
       0.8468622 , 0.01659452, 0.82538036])

In [23]:
np.random.random_sample(8)

array([0.91426814, 0.97348619, 0.77888878, 0.45243099, 0.19618828,
       0.87331567, 0.64025174, 0.49343937])

## 2. random

In [24]:
import random

In [2]:
a = list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
random.shuffle(a)

In [26]:
a

[2, 9, 6, 8, 1, 3, 4, 0, 5, 7]

In [29]:
random.choice(a)

5

In [31]:
random.randint(1, 10)

6

In [33]:
random.random()

0.4661115484230457

In [60]:
random.randrange(0, 10, 3)

6

In [61]:
random.sample(a, 3)

[0, 2, 9]